FROM python:3.9-slim

WORKDIR /app

# Install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the fixed model training script
COPY fixed_model_training.py model_training.py

# Set environment variables
ENV INPUT_FILE=/data/produits_scrapy.csv
ENV OUTPUT_DIR=/data/output

# Run the model training script
CMD ["python", "model_training.py"]