apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-model
  labels:
    app: ml-model
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ml-model
  template:
    metadata:
      labels:
        app: ml-model
    spec:
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: ecommerce-data-pvc
      - name: csv-data
        configMap:
          name: produits-scrapy-csv
      initContainers:
      - name: init-data
        image: busybox
        command: ['sh', '-c']
        args:
        - |
          mkdir -p /data/output
          echo "Copying CSV file to persistent volume..."
          cp /csv-data/produits_scrapy.csv /data/produits_scrapy.csv
          echo "Data initialization complete!"
        volumeMounts:
        - name: data-volume
          mountPath: /data
        - name: csv-data
          mountPath: /csv-data
      containers:
      - name: ml-model
        image: oumaimaboughdad/ecommerce_ml:latest
        imagePullPolicy: Always
        env:
        - name: INPUT_FILE
          value: "/data/produits_scrapy.csv"
        - name: OUTPUT_DIR
          value: "/data/output"
        volumeMounts:
        - name: data-volume
          mountPath: /data
---
apiVersion: v1
kind: Service
metadata:
  name: ml-model-service
spec:
  selector:
    app: ml-model
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP