apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-model
  labels:
    app: ml-model
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ml-model
  template:
    metadata:
      labels:
        app: ml-model
    spec:
      containers:
      - name: ml-model
        image: ${DOCKER_HUB_USERNAME}/ecommerce-ml:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: INPUT_FILE
          value: "/data/produits_scrapy.csv"
        - name: OUTPUT_DIR
          value: "/data/output"
        volumeMounts:
        - name: data-volume
          mountPath: /data
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: ecommerce-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: ml-model-service
spec:
  selector:
    app: ml-model
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP